package com.luastar.swift.tools.model.gui;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table db_config
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class DbConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_config.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_config.db_type
     *
     * @mbg.generated
     */
    private String db_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_config.db_name
     *
     * @mbg.generated
     */
    private String db_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_config.jdbc_url
     *
     * @mbg.generated
     */
    private String jdbc_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_config.user_name
     *
     * @mbg.generated
     */
    private String user_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_config.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_config.create_time
     *
     * @mbg.generated
     */
    private Date create_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column db_config.update_time
     *
     * @mbg.generated
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_config.id
     *
     * @return the value of db_config.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_config.id
     *
     * @param id the value for db_config.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_config.db_type
     *
     * @return the value of db_config.db_type
     * @mbg.generated
     */
    public String getDb_type() {
        return db_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_config.db_type
     *
     * @param db_type the value for db_config.db_type
     * @mbg.generated
     */
    public void setDb_type(String db_type) {
        this.db_type = db_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_config.db_name
     *
     * @return the value of db_config.db_name
     * @mbg.generated
     */
    public String getDb_name() {
        return db_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_config.db_name
     *
     * @param db_name the value for db_config.db_name
     * @mbg.generated
     */
    public void setDb_name(String db_name) {
        this.db_name = db_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_config.jdbc_url
     *
     * @return the value of db_config.jdbc_url
     * @mbg.generated
     */
    public String getJdbc_url() {
        return jdbc_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_config.jdbc_url
     *
     * @param jdbc_url the value for db_config.jdbc_url
     * @mbg.generated
     */
    public void setJdbc_url(String jdbc_url) {
        this.jdbc_url = jdbc_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_config.user_name
     *
     * @return the value of db_config.user_name
     * @mbg.generated
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_config.user_name
     *
     * @param user_name the value for db_config.user_name
     * @mbg.generated
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_config.password
     *
     * @return the value of db_config.password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_config.password
     *
     * @param password the value for db_config.password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_config.create_time
     *
     * @return the value of db_config.create_time
     * @mbg.generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_config.create_time
     *
     * @param create_time the value for db_config.create_time
     * @mbg.generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column db_config.update_time
     *
     * @return the value of db_config.update_time
     * @mbg.generated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column db_config.update_time
     *
     * @param update_time the value for db_config.update_time
     * @mbg.generated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }

    @Override
    public String toString() {
        return db_name;
    }

}