package com.luastar.swift.tools.model.gui;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pub_config
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class PubConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.group_code
     *
     * @mbg.generated
     */
    private String group_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.group_name
     *
     * @mbg.generated
     */
    private String group_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.config_code
     *
     * @mbg.generated
     */
    private String config_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.config_name
     *
     * @mbg.generated
     */
    private String config_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.data_id
     *
     * @mbg.generated
     */
    private String data_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.data_type
     *
     * @mbg.generated
     */
    private Integer data_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.data_content
     *
     * @mbg.generated
     */
    private String data_content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.data_sort
     *
     * @mbg.generated
     */
    private Long data_sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.data_status
     *
     * @mbg.generated
     */
    private Integer data_status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.data_p1
     *
     * @mbg.generated
     */
    private String data_p1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.data_p2
     *
     * @mbg.generated
     */
    private String data_p2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.data_p3
     *
     * @mbg.generated
     */
    private String data_p3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.data_p4
     *
     * @mbg.generated
     */
    private String data_p4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.data_p5
     *
     * @mbg.generated
     */
    private String data_p5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.create_time
     *
     * @mbg.generated
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_config.update_time
     *
     * @mbg.generated
     */
    private Date update_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.id
     *
     * @return the value of pub_config.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.id
     *
     * @param id the value for pub_config.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.group_code
     *
     * @return the value of pub_config.group_code
     *
     * @mbg.generated
     */
    public String getGroup_code() {
        return group_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.group_code
     *
     * @param group_code the value for pub_config.group_code
     *
     * @mbg.generated
     */
    public void setGroup_code(String group_code) {
        this.group_code = group_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.group_name
     *
     * @return the value of pub_config.group_name
     *
     * @mbg.generated
     */
    public String getGroup_name() {
        return group_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.group_name
     *
     * @param group_name the value for pub_config.group_name
     *
     * @mbg.generated
     */
    public void setGroup_name(String group_name) {
        this.group_name = group_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.config_code
     *
     * @return the value of pub_config.config_code
     *
     * @mbg.generated
     */
    public String getConfig_code() {
        return config_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.config_code
     *
     * @param config_code the value for pub_config.config_code
     *
     * @mbg.generated
     */
    public void setConfig_code(String config_code) {
        this.config_code = config_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.config_name
     *
     * @return the value of pub_config.config_name
     *
     * @mbg.generated
     */
    public String getConfig_name() {
        return config_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.config_name
     *
     * @param config_name the value for pub_config.config_name
     *
     * @mbg.generated
     */
    public void setConfig_name(String config_name) {
        this.config_name = config_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.data_id
     *
     * @return the value of pub_config.data_id
     *
     * @mbg.generated
     */
    public String getData_id() {
        return data_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.data_id
     *
     * @param data_id the value for pub_config.data_id
     *
     * @mbg.generated
     */
    public void setData_id(String data_id) {
        this.data_id = data_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.data_type
     *
     * @return the value of pub_config.data_type
     *
     * @mbg.generated
     */
    public Integer getData_type() {
        return data_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.data_type
     *
     * @param data_type the value for pub_config.data_type
     *
     * @mbg.generated
     */
    public void setData_type(Integer data_type) {
        this.data_type = data_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.data_content
     *
     * @return the value of pub_config.data_content
     *
     * @mbg.generated
     */
    public String getData_content() {
        return data_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.data_content
     *
     * @param data_content the value for pub_config.data_content
     *
     * @mbg.generated
     */
    public void setData_content(String data_content) {
        this.data_content = data_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.data_sort
     *
     * @return the value of pub_config.data_sort
     *
     * @mbg.generated
     */
    public Long getData_sort() {
        return data_sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.data_sort
     *
     * @param data_sort the value for pub_config.data_sort
     *
     * @mbg.generated
     */
    public void setData_sort(Long data_sort) {
        this.data_sort = data_sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.data_status
     *
     * @return the value of pub_config.data_status
     *
     * @mbg.generated
     */
    public Integer getData_status() {
        return data_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.data_status
     *
     * @param data_status the value for pub_config.data_status
     *
     * @mbg.generated
     */
    public void setData_status(Integer data_status) {
        this.data_status = data_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.data_p1
     *
     * @return the value of pub_config.data_p1
     *
     * @mbg.generated
     */
    public String getData_p1() {
        return data_p1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.data_p1
     *
     * @param data_p1 the value for pub_config.data_p1
     *
     * @mbg.generated
     */
    public void setData_p1(String data_p1) {
        this.data_p1 = data_p1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.data_p2
     *
     * @return the value of pub_config.data_p2
     *
     * @mbg.generated
     */
    public String getData_p2() {
        return data_p2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.data_p2
     *
     * @param data_p2 the value for pub_config.data_p2
     *
     * @mbg.generated
     */
    public void setData_p2(String data_p2) {
        this.data_p2 = data_p2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.data_p3
     *
     * @return the value of pub_config.data_p3
     *
     * @mbg.generated
     */
    public String getData_p3() {
        return data_p3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.data_p3
     *
     * @param data_p3 the value for pub_config.data_p3
     *
     * @mbg.generated
     */
    public void setData_p3(String data_p3) {
        this.data_p3 = data_p3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.data_p4
     *
     * @return the value of pub_config.data_p4
     *
     * @mbg.generated
     */
    public String getData_p4() {
        return data_p4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.data_p4
     *
     * @param data_p4 the value for pub_config.data_p4
     *
     * @mbg.generated
     */
    public void setData_p4(String data_p4) {
        this.data_p4 = data_p4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.data_p5
     *
     * @return the value of pub_config.data_p5
     *
     * @mbg.generated
     */
    public String getData_p5() {
        return data_p5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.data_p5
     *
     * @param data_p5 the value for pub_config.data_p5
     *
     * @mbg.generated
     */
    public void setData_p5(String data_p5) {
        this.data_p5 = data_p5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.create_time
     *
     * @return the value of pub_config.create_time
     *
     * @mbg.generated
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.create_time
     *
     * @param create_time the value for pub_config.create_time
     *
     * @mbg.generated
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_config.update_time
     *
     * @return the value of pub_config.update_time
     *
     * @mbg.generated
     */
    public Date getUpdate_time() {
        return update_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_config.update_time
     *
     * @param update_time the value for pub_config.update_time
     *
     * @mbg.generated
     */
    public void setUpdate_time(Date update_time) {
        this.update_time = update_time;
    }
}