CREATE TABLE IF NOT EXISTS `DB_CONFIG` (
  `ID`          INT(8)    NOT NULL AUTO_INCREMENT,
  `DB_TYPE`     VARCHAR(256)       DEFAULT NULL,
  `DB_NAME`     VARCHAR(256)       DEFAULT NULL,
  `JDBC_URL`    VARCHAR(1024)      DEFAULT NULL,
  `USER_NAME`   VARCHAR(256)       DEFAULT NULL,
  `PASSWORD`    VARCHAR(256)       DEFAULT NULL,
  `CREATE_TIME` DATETIME           DEFAULT NULL,
  `UPDATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `PUB_CONFIG` (
  `ID`           INT(20)   NOT NULL AUTO_INCREMENT,
  `GROUP_CODE`   VARCHAR(256)       DEFAULT NULL,
  `GROUP_NAME`   VARCHAR(256)       DEFAULT NULL,
  `CONFIG_CODE`  VARCHAR(256)       DEFAULT NULL,
  `CONFIG_NAME`  VARCHAR(256)       DEFAULT NULL,
  `DATA_ID`      VARCHAR(256)       DEFAULT NULL,
  `DATA_TYPE`    INT(8)             DEFAULT NULL,
  `DATA_CONTENT` VARCHAR(2048)      DEFAULT NULL,
  `DATA_SORT`    BIGINT(20)         DEFAULT NULL,
  `DATA_STATUS`  INT(4)             DEFAULT NULL,
  `DATA_P1`      VARCHAR(1024)      DEFAULT NULL,
  `DATA_P2`      VARCHAR(1024)      DEFAULT NULL,
  `DATA_P3`      VARCHAR(1024)      DEFAULT NULL,
  `DATA_P4`      VARCHAR(1024)      DEFAULT NULL,
  `DATA_P5`      VARCHAR(1024)      DEFAULT NULL,
  `CREATE_TIME`  DATETIME           DEFAULT NULL,
  `UPDATE_TIME`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  KEY `IDX_GROUP_CODE` (`GROUP_CODE`),
  UNIQUE KEY `UNI_CONFIG_CODE` (`CONFIG_CODE`)
);